from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
import datetime
import os


def generate_pdf(report_path,
                 image_name,
                 defects,
                 average_confidence,
                 status):

    c = canvas.Canvas(report_path, pagesize=A4)

    width, height = A4

    # ==========================
    # Header
    # ==========================

    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 40,
                        "AI MATERIAL INSPECTION REPORT")

    c.setStrokeColor(colors.blue)
    c.setLineWidth(2)
    c.line(40, height - 55, width - 40, height - 55)

    # ==========================
    # Report Details
    # ==========================

    c.setFont("Helvetica", 11)

    c.drawString(
        50,
        height - 90,
        f"Report ID : {datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"
    )

    c.drawString(
        50,
        height - 110,
        f"Date : {datetime.datetime.now().strftime('%d-%m-%Y')}"
    )

    c.drawString(
        50,
        height - 130,
        f"Time : {datetime.datetime.now().strftime('%H:%M:%S')}"
    )

    c.drawString(
        50,
        height - 150,
        f"Image : {image_name}"
    )

    # ==========================
    # Original Image
    # ==========================

    upload_path = os.path.join(
        "static",
        "uploads",
        image_name
    )

    if os.path.exists(upload_path):

        c.setFont("Helvetica-Bold", 13)

        c.drawString(
            50,
            height - 185,
            "Original Image"
        )

        img = ImageReader(upload_path)

        c.drawImage(
            img,
            50,
            height - 380,
            width=200,
            height=170,
            preserveAspectRatio=True
        )

    # ==========================
    # Detected Image
    # ==========================

    result_path = os.path.join(
        "static",
        "results",
        image_name
    )

    if os.path.exists(result_path):

        c.setFont("Helvetica-Bold", 13)

        c.drawString(
            320,
            height - 185,
            "Detected Image"
        )

        img = ImageReader(result_path)

        c.drawImage(
            img,
            320,
            height - 380,
            width=200,
            height=170,
            preserveAspectRatio=True
        )

    # ==========================
    # Defect Table
    # ==========================

    table_data = [["Defect", "Confidence (%)"]]

    if len(defects) == 0:

        table_data.append(["No Defect", "0"])

    else:

        for defect in defects:

            table_data.append([
                defect["name"],
                str(defect["confidence"])
            ])

    table = Table(table_data, colWidths=[220, 120])

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.blue),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

    ]))

    table.wrapOn(c, width, height)

    table.drawOn(c, 90, height - 620)

    # ==========================
    # Status
    # ==========================

    c.setFont("Helvetica-Bold", 15)

    c.drawString(
        50,
        130,
        f"Inspection Status : {status}"
    )

    c.drawString(
        50,
        105,
        f"Average Confidence : {average_confidence:.2f}%"
    )

    # ==========================
    # Footer
    # ==========================

    c.setStrokeColor(colors.grey)

    c.line(40, 70, width - 40, 70)

    c.setFont("Helvetica", 10)

    c.drawCentredString(
        width / 2,
        50,
        "Generated by AI Material Inspection System"
    )

    c.save()